CREATE DATABASE STONKS;
USE STONKS;



CREATE TABLE USERS
(
	UserN VARCHAR(15) NOT NULL,
    PassW VARCHAR(15) NOT NULL
);

CREATE TABLE STOCKS
(
	Date DATE NOT NULL,
	Token CHAR(4) NOT NULL,
    AdjClose INT NOT NULL,
    CloseP INT NOT NULL,
    HighP INT NOT NULL,
    LowP INT NOT NULL,
    OpenP INT NOT NULL,
    Volume INT NOT NULL
);

INSERT INTO USERS(UserN, PassW) VALUES
				("admin", "guy")UserNUserNPassWUSERS;

